### ISSUE TITLE
微信支付回调 xml 数据为空 无法正常解析

### ISSUE THREAD

**Issue by jackey-jiang** [chillzhuang/blade-tool#5]
你好, 目前用了这套tool, jackson 无法正常转化xml, 微信支付回调数据会变成空字符串,求助大佬,该如何是好

**Comment by jackey-jiang** [comment]
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g8ncwffpe5j30j80dtaix.jpg)
是否 删除这段即可?

**Comment by chillzhuang** [comment]
删掉或者看这个：https://sns.bladex.vip/q-112.html


    


            在2019年11月05日 18:50，江易疯先森 写道： 

是否 删除这段即可?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/chillzhuang/blade-tool/issues/5?email_source=notifications\u0026email_token=AAZWVFU5XN2IHAROUI7OELDQSFFWHA5CNFSM4JJAZLQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDCNKMY#issuecomment-549770547",

"url": "https://github.com/chillzhuang/blade-tool/issues/5?email_source=notifications\u0026email_token=AAZWVFU5XN2IHAROUI7OELDQSFFWHA5CNFSM4JJAZLQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDCNKMY#issuecomment-549770547",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
